javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/autocomplete-rails.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
    - public/stylesheets/css3buttons/css3buttons.css
    - public/stylesheets/podcast.css

  episodes:
    - public/stylesheets/episode.css